# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1146, 586)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 164, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 164, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 164, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 164, 68))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exportbutton = QtWidgets.QPushButton(self.centralwidget)
        self.exportbutton.setGeometry(QtCore.QRect(920, 420, 181, 51))
        self.exportbutton.setObjectName("exportbutton")
        self.FileInputBox = QtWidgets.QGroupBox(self.centralwidget)
        self.FileInputBox.setGeometry(QtCore.QRect(10, 70, 261, 261))
        self.FileInputBox.setObjectName("FileInputBox")
        self.filelist = QtWidgets.QListWidget(self.FileInputBox)
        self.filelist.setGeometry(QtCore.QRect(5, 20, 251, 231))
        self.filelist.setInputMethodHints(QtCore.Qt.ImhNone)
        self.filelist.setObjectName("filelist")
        self.OptionsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.OptionsBox.setGeometry(QtCore.QRect(280, 70, 261, 261))
        self.OptionsBox.setObjectName("OptionsBox")
        self.radioButton_Hap = QtWidgets.QRadioButton(self.OptionsBox)
        self.radioButton_Hap.setGeometry(QtCore.QRect(20, 30, 51, 20))
        self.radioButton_Hap.setObjectName("radioButton_Hap")
        self.radioButton_HapQ = QtWidgets.QRadioButton(self.OptionsBox)
        self.radioButton_HapQ.setGeometry(QtCore.QRect(20, 140, 71, 20))
        self.radioButton_HapQ.setObjectName("radioButton_HapQ")
        self.radioButton_HapAlpha = QtWidgets.QRadioButton(self.OptionsBox)
        self.radioButton_HapAlpha.setGeometry(QtCore.QRect(20, 90, 101, 20))
        self.radioButton_HapAlpha.setObjectName("radioButton_HapAlpha")
        self.radioButton_Mjpeg = QtWidgets.QRadioButton(self.OptionsBox)
        self.radioButton_Mjpeg.setGeometry(QtCore.QRect(20, 190, 61, 20))
        self.radioButton_Mjpeg.setObjectName("radioButton_Mjpeg")
        self.RenamingBox = QtWidgets.QGroupBox(self.centralwidget)
        self.RenamingBox.setGeometry(QtCore.QRect(550, 70, 261, 261))
        self.RenamingBox.setObjectName("RenamingBox")
        self.removeInput = QtWidgets.QTextEdit(self.RenamingBox)
        self.removeInput.setGeometry(QtCore.QRect(10, 70, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.removeInput.setFont(font)
        self.removeInput.setObjectName("removeInput")
        self.label_3 = QtWidgets.QLabel(self.RenamingBox)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 171, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.RenamingBox)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 221, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.RenamingBox)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 221, 16))
        self.label_5.setObjectName("label_5")
        self.prefixInput = QtWidgets.QTextEdit(self.RenamingBox)
        self.prefixInput.setGeometry(QtCore.QRect(10, 170, 231, 51))
        self.prefixInput.setObjectName("prefixInput")
        self.OutputBox = QtWidgets.QGroupBox(self.centralwidget)
        self.OutputBox.setGeometry(QtCore.QRect(820, 70, 301, 261))
        self.OutputBox.setObjectName("OutputBox")
        self.Output_dir_textEdit = QtWidgets.QTextEdit(self.OutputBox)
        self.Output_dir_textEdit.setGeometry(QtCore.QRect(10, 40, 271, 23))
        self.Output_dir_textEdit.setObjectName("Output_dir_textEdit")
        self.label_6 = QtWidgets.QLabel(self.OutputBox)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 171, 21))
        self.label_6.setObjectName("label_6")
        self.resolution_comboBox = QtWidgets.QComboBox(self.OutputBox)
        self.resolution_comboBox.setGeometry(QtCore.QRect(30, 170, 201, 22))
        self.resolution_comboBox.setObjectName("resolution_comboBox")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.orig_resolution_checkBox = QtWidgets.QCheckBox(self.OutputBox)
        self.orig_resolution_checkBox.setGeometry(QtCore.QRect(10, 130, 201, 20))
        self.orig_resolution_checkBox.setChecked(True)
        self.orig_resolution_checkBox.setObjectName("orig_resolution_checkBox")
        self.predefined_label = QtWidgets.QLabel(self.OutputBox)
        self.predefined_label.setGeometry(QtCore.QRect(30, 150, 141, 16))
        self.predefined_label.setObjectName("predefined_label")
        self.checkBox = QtWidgets.QCheckBox(self.OutputBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 200, 131, 17))
        self.checkBox.setObjectName("checkBox")
        self.textEdit = QtWidgets.QTextEdit(self.OutputBox)
        self.textEdit.setGeometry(QtCore.QRect(70, 220, 61, 23))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.OutputBox)
        self.textEdit_2.setGeometry(QtCore.QRect(200, 220, 61, 23))
        self.textEdit_2.setObjectName("textEdit_2")
        self.w_label = QtWidgets.QLabel(self.OutputBox)
        self.w_label.setGeometry(QtCore.QRect(30, 220, 31, 16))
        self.w_label.setObjectName("w_label")
        self.w_label_2 = QtWidgets.QLabel(self.OutputBox)
        self.w_label_2.setGeometry(QtCore.QRect(160, 220, 31, 16))
        self.w_label_2.setObjectName("w_label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 520, 821, 16))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 490, 1131, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.title_cheesy = QtWidgets.QLabel(self.centralwidget)
        self.title_cheesy.setGeometry(QtCore.QRect(14, 15, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.title_cheesy.setFont(font)
        self.title_cheesy.setObjectName("title_cheesy")
        self.pixmap_label_7 = QtWidgets.QLabel(self.centralwidget)
        self.pixmap_label_7.setGeometry(QtCore.QRect(130, 10, 71, 61))
        self.pixmap_label_7.setAcceptDrops(True)
        self.pixmap_label_7.setObjectName("pixmap_label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1146, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSIMPLE_HAP_BATCH_EXPORTER = QtWidgets.QAction(MainWindow)
        self.actionSIMPLE_HAP_BATCH_EXPORTER.setObjectName("actionSIMPLE_HAP_BATCH_EXPORTER")
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.filelist.setCurrentRow(-1)
        self.orig_resolution_checkBox.toggled['bool'].connect(self.resolution_comboBox.setDisabled)
        self.orig_resolution_checkBox.toggled['bool'].connect(self.predefined_label.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exportbutton.setText(_translate("MainWindow", "Export!"))
        self.FileInputBox.setTitle(_translate("MainWindow", "Files"))
        self.OptionsBox.setTitle(_translate("MainWindow", "Options"))
        self.radioButton_Hap.setText(_translate("MainWindow", "HAP "))
        self.radioButton_HapQ.setText(_translate("MainWindow", "HAP  Q"))
        self.radioButton_HapAlpha.setText(_translate("MainWindow", "HAP + Alpha"))
        self.radioButton_Mjpeg.setText(_translate("MainWindow", "MJPEG"))
        self.RenamingBox.setTitle(_translate("MainWindow", "Renaming Options"))
        self.label_3.setText(_translate("MainWindow", "Remove Strings in Filenames"))
        self.label_4.setText(_translate("MainWindow", "seperate through \";\""))
        self.label_5.setText(_translate("MainWindow", "add Prefix:"))
        self.OutputBox.setTitle(_translate("MainWindow", "Output"))
        self.Output_dir_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Output Directory: "))
        self.resolution_comboBox.setItemText(0, _translate("MainWindow", "1920x1080"))
        self.resolution_comboBox.setItemText(1, _translate("MainWindow", "1280x720"))
        self.resolution_comboBox.setItemText(2, _translate("MainWindow", "600x200"))
        self.orig_resolution_checkBox.setText(_translate("MainWindow", "Use source original resolution"))
        self.predefined_label.setText(_translate("MainWindow", "Use predefined resolutions"))
        self.checkBox.setText(_translate("MainWindow", "Use custom resolution"))
        self.w_label.setText(_translate("MainWindow", "width:"))
        self.w_label_2.setText(_translate("MainWindow", "height:"))
        self.label.setText(_translate("MainWindow", "CheesyHAP Batch Hap Converter/Exporter v 0.1 by Artur Kechter, based on ffmpeg"))
        self.title_cheesy.setText(_translate("MainWindow", "CheesyHAP"))
        self.pixmap_label_7.setText(_translate("MainWindow", "Cheese Place"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionSIMPLE_HAP_BATCH_EXPORTER.setText(_translate("MainWindow", "SIMPLE HAP BATCH EXPORTER"))
